### ISSUE TITLE
Old Scoreboard doesn't update when a player leaves

### ISSUE THREAD

**Issue by iCHOPPERi** [YaLTeR/OpenAG#119]
Old Scoreboard doesn't update after a player leaves while you keep it open via the +showscores command causing them to show as (null) in the scoreboard

**Comment by chinese-soup** [comment]
Alright thanks, will check it out tomorrow. :)

**Comment by chinese-soup** [comment]
@iCHOPPERi Hello. Did this happen to you on any dedicated server or only on a local one started from the menu / console (`maxplayers x; deathmatch 1; map crossfire`)?

I am asking since I can only reproduce this on a server that's being hosted in the same instance as the client - aka a local server. 

I've tried reproducing it on several dedicated servers (Ironanjuu, 2 of SourceRuns, local HLDS even) and couldn't get this bug anywhere, so I am assuming it has to do something with the fact the client is hosting the server and doesn't update the client (or the client is "reading" something that he usually can't when not in the same engine as the server) or something.

**Comment by iCHOPPERi** [comment]
It happened to me on DE 1 if I remember correctly and yes it happened on local servers aswell

**Comment by iCHOPPERi** [comment]
![2021-06-04_20-13](https://user-images.githubusercontent.com/22107981/120839552-9c006e80-c558-11eb-82c8-c42f51e6bcf6.png)
While we're at it, I took another picture of it happening on DE 1 today

**Comment by chinese-soup** [comment]
Alright, I can consistently reproduce it there, will try to find a fix, thanks for the info. :)
