### ISSUE TITLE
OpenAG crashes after Half-Life 25th Anniversary Update

### ISSUE THREAD

**Issue by GTManiK** [YaLTeR/OpenAG#180]
Hopefully someone fixes this. The game crashes when you:
- attempt to start a listen server
- attempt to join a server

**Comment by YaLTeR** [comment]
Yeah we're waiting for the updated HLSDK I guess. For now please use the legacy Beta on Half-Life.

**Comment by SmileyAG** [comment]
![new_update](https://github.com/YaLTeR/OpenAG/assets/58108407/9151e72b-1631-48d6-9f6d-b11febc8ef28)

A new engine update has fixed the issue with a crash for some mods, I got tested that rn in OpenAG and seems it's not a more issue with connecting to some servers so that could be closed

Although, it crashes when I start the local server, but I bet there something weird with own version of `ag.dll`, and even I haven't runned debug for it yet I don't think there any traces from OpenAG that could affect to it (because that doesn't cause crash with connecting to other servers)

**Comment by YaLTeR** [comment]
Neat
